---
user: ankita
group: ankita
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
port : 81
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
socket: tmp/sockets/thin.sock
chdir: /var/www/html/recipe-app-thin/current
tag: recipe-app-thin